name: "Captain CI example"
on:
  pull_request:
  push:
    paths-ignore:
      - README.md
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm clean-install
      - uses: rwx-research/setup-captain@v1
      - uses: browser-actions/setup-chrome@v1
      - run: |
          captain run \
            --suite-id captain-examples-karma \
            --test-results "tmp/results.json" \
            -- \
            npm test
        env:
          RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}
